dist: trusty
sudo: true

cache:
  apt: true

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - CC=gcc-5
        - CXX=g++-5
        - CXXFLAGS="-std=c++14 -Wpedantic -Wall -Wextra"

    - compiler: clang
      env:
        - CC=clang
        - CXX=clang++
        - CXXFLAGS="-std=c++14 -Wpedantic -Wall -Wextra"

script:
  - cmake .
  - cmake --build . -- -j2
  - ctest
